# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - sh -c "if [ ! -f tmpl/kube-config.yaml ]; then cp -v assets/kube-config.yaml tmpl/kube-config.yaml; fi"
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/gini/dexter/version.VERSION={{.Version}}
      - -X github.com/gini/dexter/version.GITHASH={{.Commit}}
      - -X github.com/gini/dexter/version.DOB={{.Date}}
      - -X github.com/gini/dexter/cmd.buildTimeClientID={{ if index .Env "CLIENT_ID" }}{{ .Env.CLIENT_ID }}{{ else }}""{{ end }}
      - -X github.com/gini/dexter/cmd.buildTimeClientSecret={{ if index .Env "CLIENT_SECRET" }}{{ .Env.CLIENT_SECRET }}{{ else }}""{{ end }}
      - -X github.com/gini/dexter/cmd.buildTimeProvider={{ if index .Env "DEFAULT_PROVIDER" }}{{ .Env.DEFAULT_PROVIDER }}{{ else }}""{{ end }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
universal_binaries:
  - replace: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

